# Generated by Django 3.0.6 on 2020-05-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('learning_link', models.URLField()),
                ('description', models.TextField()),
                ('use_case', models.TextField()),
                ('ease_of_use', models.CharField(choices=[('Simple', 'Simple'), ('Moderate', 'Moderate'), ('Advanced', 'Advanced')], max_length=20)),
                ('price', models.CharField(choices=[('0', 'No cost to you'), ('$', '$'), ('$$', '$$'), ('$$$', '$$$')], max_length=5)),
                ('website', models.URLField()),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtertools.Tool')),
            ],
        ),
    ]
