# Generated by Django 3.0.6 on 2020-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtertools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='voicethread'),
            preserve_default=False,
        ),
    ]
