# Generated by Django 3.0.6 on 2020-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtertools', '0002_tool_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Collaboration', 'Collaboration'), ('Videos', 'Videos'), ('Productivity', 'Productivity'), ('Web', 'ePortfolios and Websites'), ('Response', 'Classroom Response'), ('Integrity', 'Academic Integrity'), ('Resources', 'Educational Resources'), ('Grading', 'Assessment and Grading')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Tool'},
        ),
        migrations.AddField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(to='filtertools.Categories'),
        ),
    ]
