# Generated by Django 3.0.6 on 2020-05-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtertools', '0004_categories_tooltip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
