# Generated by Django 3.0.6 on 2020-05-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtertools', '0005_auto_20200528_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='verbose_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.CharField(choices=[('Collaboration', 'Collaboration'), ('Videos', 'Videos'), ('Productivity', 'Productivity'), ('Web', 'ePortfolios and Websites'), ('Response', 'Classroom Response'), ('Integrity', 'Academic Integrity'), ('Resources', 'Educational Resources'), ('Grading', 'Assessment and Grading')], max_length=20, unique=True),
        ),
    ]
