# Generated by Django 3.0.6 on 2020-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtertools', '0006_auto_20200528_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.CharField(help_text='A short, unique tag for internal use by the webpage. Not visible, and must not have spaces.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='tooltip',
            field=models.CharField(help_text='The text that is visible when hovering over the category button.', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='verbose_name',
            field=models.CharField(help_text='The public-facing name of this category.', max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(help_text='A description of the tool that is only visible once the "Read More" button is clicked.'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='publish',
            field=models.BooleanField(default=False, help_text='Not yet functional.'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(help_text='A short version of the title of the tool with no spaces used if a page is built for the tool, for example mainpage.com/[slug].', unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='use_case',
            field=models.TextField(help_text='Should answer the prompt, "You might use this tool if..." and be written in the 2nd person.'),
        ),
    ]
